import { GridColDef } from "@mui/x-data-grid";

export const columns: GridColDef[] = [
  {
    field: "name",
    headerName: "Pracownicy",
    width: 200,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "1",
    headerName: "1",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "2",
    headerName: "2",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "3",
    headerName: "3",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "4",
    headerName: "4",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "5",
    headerName: "5",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "6",
    headerName: "6",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "7",
    headerName: "7",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "8",
    headerName: "8",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "9",
    headerName: "9",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "10",
    headerName: "10",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "11",
    headerName: "11",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "12",
    headerName: "12",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "13",
    headerName: "13",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "14",
    headerName: "14",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "15",
    headerName: "15",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "16",
    headerName: "16",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "17",
    headerName: "17",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "18",
    headerName: "18",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "19",
    headerName: "19",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "20",
    headerName: "20",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "21",
    headerName: "21",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "22",
    headerName: "22",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "23",
    headerName: "23",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "24",
    headerName: "24",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "25",
    headerName: "25",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "26",
    headerName: "26",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "27",
    headerName: "27",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "28",
    headerName: "28",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "29",
    headerName: "29",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "30",
    headerName: "30",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
  {
    field: "31",
    headerName: "31",
    width: 150,
    editable: true,
    headerClassName: "super-app-theme--header",
  },
];
